### ISSUE TITLE
Internal Server Error when trying to check-in

### ISSUE THREAD

**Issue by felipe-actec** [Nibblecomm/spotipo#5]
Once we already chatted in discuss community, I'm just registering the issue as the developer asked.

The link of the conversation is below.

https://discuss.spotipo.com/d/283-internal-server-error-when-trying-to-check-in

**Comment by rakeshmukundan** [comment]
#

**Comment by rakeshmukundan** [comment]
Fixed with commit 334f65f373182b80c2bb4ef34708356d280340e2
